hub:
  baseUrl: /jupyterhub-internal/
  db:
    type: sqlite-memory
  extraConfig: |
    # https://github.com/jupyterhub/jupyterhub/wiki/Debug-Jupyterhub
    c.JupyterHub.log_level = 'DEBUG'
    c.Spawner.debug = True
    c.KubeSpawner.singleuser_image_pull_policy = 'Always'

#auth: secret

proxy:
  #secretToken: secret: openssl rand -hex 32
  service:
    type: ClusterIP

singleuser:
  # Must be compatible with JupyterHub 0.8
  image:
    name: manics/jupyter-docker
    tag: jupyterhub-0.8
  startTimeout: 600
  memory:
    limit: 1G
    guarantee: 100M
  storage:
    type: NONE
  #extraEnv: secret

# Disable image pre-puller
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

ingress:
  enabled: true
  hosts:
  - ome-lochy.openmicroscopy.org
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 16m
    ingress.kubernetes.io/proxy-read-timeout: 3600
    ingress.kubernetes.io/proxy-send-timeout: 3600
    #kubernetes.io/tls-acme: 'true'
  tls:
  - hosts:
    - ome-lochy.openmicroscopy.org
